### ISSUE TITLE
Card art

### ISSUE THREAD

**Issue by KAMAQUEEN** [celebo/hakumod#1]
In the base game every card has a colored background, attacks have red background, skills have blue background, unless they're on more of an offensive side, then they have red background as well, and powers do whatever they want. That way you can tell which card does what from just glancing over you hand\deck which is really handy. Hakumen however does not have this little touch, and with lots of cards looking extremely similar it makes things even worse, so it would've been nice to have that feature

**Comment by celebo** [comment]
Good evening, the mod has just been updated with new artworks for most cards.
